# Spring boot application
spring:
  application:
    name: ztc-vegetable-manage-restful
  datasource:
    druid:
      url: jdbc:mysql://mysql.ztc.mobi:3306/vegetable-shop?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: ztc
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088

# UserService service version
user:
  service:
    version: 1.0.0

# Dubbo Config properties
dubbo:
  ## ApplicationConfig Bean
  application:
    id: ztc-vegetable-manage-restful
    name: ztc-vegetable-manage-restful
  ## RegistryConfig Bean
  #  scan:
  #    basePackages: com.funtl.hello.dubbo.service.user
  registry:
    id: zookeeper
    #    address: zookeeper://192.168.91.147:2181?backup=192.168.91.147:2182,192.168.91.147:2183
    address: zookeeper://127.0.0.1:2181
    protocol:
      id: dubbo
      name: dubbo
# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true
management:
  server:
    port: 9091
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
  # Enables Dubbo All Endpoints

mybatis:
  type-aliases-package: com.ztc.vegetable.manage.db.model
  mapper-locations: classpath:com/ztc/vegetable/manage/db/mapper/*/*.xml
